const SET_IS_AUTH = 'SET_IS_AUTH';
const SET_USER = 'SET_USER';

const SET_CLEANERS = 'SET_CLEANERS';
const SET_CUSTOMERS = 'SET_CUSTOMERS';
const SET_ADDRESSES = 'SET_ADDRESSES';
const SET_ACTIVE_JOBS = 'SET_ACTIVE_JOBS';
const SET_PAST_JOBS = 'SET_PAST_JOBS';
const SET_ADJUSTMENT_JOBS = 'SET_ADJUSTMENT_JOBS';
const SET_CANCELLED_JOBS = 'SET_CANCELLED_JOBS';
const SET_ORDERS = 'SET_ORDERS';
const SET_CANCELLED_ORDERS = 'SET_CANCELLED_ORDERS';

export {
  SET_IS_AUTH,
  SET_USER,
  SET_CLEANERS,
  SET_CUSTOMERS,
  SET_ADDRESSES,
  SET_ACTIVE_JOBS,
  SET_PAST_JOBS,
  SET_ADJUSTMENT_JOBS,
  SET_CANCELLED_JOBS,
  SET_ORDERS,
  SET_CANCELLED_ORDERS,
};
