const SET_IS_AUTH = 'SET_IS_AUTH';
const SET_IP_COUNTRY = 'SET_IP_COUNTRY';
const SET_USER = 'SET_USER';

const SET_CLEANERS = 'SET_CLEANERS';
const SET_CUSTOMERS = 'SET_CUSTOMERS';
const SET_ACTIVE_JOBS = 'SET_ACTIVE_JOBS';
const SET_PAST_JOBS = 'SET_PAST_JOBS';
const SET_ADJUSTMENT_JOBS = 'SET_ADJUSTMENT_JOBS';
const SET_CANCELLED_JOBS = 'SET_CANCELLED_JOBS';
const SET_ORDERS = 'SET_ORDERS';
const SET_CANCELLED_ORDERS = 'SET_CANCELLED_ORDERS';
const SET_CONTACT_REQUESTS = 'SET_CONTACT_REQUESTS';

const SET_CLEANER = 'SET_CLEANER';
const SET_CUSTOMER = 'SET_CUSTOMER';
const SET_ADDRESS = 'SET_ADDRESS';
const SET_CLEANING = 'SET_CLEANING';
const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';

export {
  SET_IS_AUTH,
  SET_IP_COUNTRY,
  SET_USER,
  SET_CLEANERS,
  SET_CUSTOMERS,
  SET_ACTIVE_JOBS,
  SET_PAST_JOBS,
  SET_ADJUSTMENT_JOBS,
  SET_CANCELLED_JOBS,
  SET_ORDERS,
  SET_CANCELLED_ORDERS,
  SET_CONTACT_REQUESTS,
  SET_CLEANER,
  SET_CUSTOMER,
  SET_ADDRESS,
  SET_CLEANING,
  SET_SUBSCRIPTION,
};
